#!/bin/bash

# Current working directory
CWD=`cd $(dirname $0) && pwd`

echo "export PATH=$CWD:$PATH" >> $HOME/.bashrc

#Give executable permissions if it doesn't have it
for x in genUser permit updateBranch allotInterest makeTransaction genSummary
do
	chmod +x $CWD/$x
done
