#!/bin/bash
#Not with executable permissions by default
for ((i=1;i<=50;i++));do
	userdel ACC`printf %04d $i`
done

for i in 1 2 3 4; do userdel Branch$i;done
userdel ceo
for i in omega{Users,Managers,Ceo} legacy citizen seniorCitizen resident foreigner minor;do
	groupdel $i
done

rm log_files/*

#rm -r /home/OmegaServer
