#!/bin/bash

. config

read -p "Enter your branch number: " bNo
BRANCH_DIR=$SERVER_DIR/Branch$bNo
unset bNo

if ! [ -d $BRANCH_DIR ]; then
	echo "Branch not exists"
	exit -1
fi
# The max accounts should be restricted to 9999
branchBalance=0
for userAcc in $BRANCH_DIR/ACC????; do
	branchBalance=$[ branchBalance + `cat $userAcc/Current_Balance.txt` ]
#TODO: Need to sort transactions based on date
	cat $userAcc/Transaction_History.txt >> $BRANCH_DIR/Branch_Transaction_History.txt
done

echo $branchBalance > $BRANCH_DIR/Branch_Current_Balance.txt
